name: GitHub Release Demo
run-name: ${{ github.actor }} is trying to set up release automation 🚀
on: [push]
jobs:
  releaseLTFAT:
    runs-on: ubuntu-latest
    steps:
      - name: Check out ltfat repository
        uses: actions/checkout@v3
      - name: Update ubuntu
        run: sudo apt-get update
      - name: Install Octave
        run: sudo apt-get install octave
      - name: Check out mat2doc repository
        uses: actions/checkout@master
        with:
          name: ltfat/mat2doc     <-- clone https://github.com/ltfat/mat2doc
          path: ./mat2doc_exec
      - name: Move to mat2doc directory
        run: cd ${{ github.workspace }}
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install Python packages
        run: pip install numpy scipy
      - name: Run mat2doc directory
        run: ./mat2doc_exec/mat2doc.py --h

