name: LTFAT Deployment
run-name: ${{ github.actor }} is slowly getting there... 🚀
on: [push]
jobs:
  setup ltfat and mat2doc:
    runs-on: ubuntu-latest
    steps:
      - name: Update ubuntu
        run: sudo apt-get update
      - name: Check out ltfat repository
        uses: actions/checkout@v3
      - name: Install Octave
        run: sudo apt-get install octave
      - name: Check out mat2doc repository
        uses: actions/checkout@master
        with:
          repository: ltfat/mat2doc
          path: './mat2doc_exec'
      - name: Install Bibtex2html
        run: sudo apt-get install -y bibtex2html
      - name: Install Bibtex2html
        run: sudo apt-get install lynx
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install Python packages
        run: pip install numpy scipy docutils
  do mat files:
    needs: setup ltfat and mat2doc
      - name: Generate mat files
        run: ./mat2doc_exec/mat2doc.py ./ltfat/ltfat mat
  do html files:
    needs: [setup ltfat and mat2doc, do mat files]
      - name: Generate tex files
        run: ./mat2doc_exec/mat2doc.py ./ltfat/ltfat tex

